DROP TABLE FOODCOMMENTS;
CREATE TABLE FOODCOMMENTS (
    FCID NUMBER NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    F_COMMENT VARCHAR(2000)
);
/

DROP SEQUENCE FC_SQ;
CREATE SEQUENCE FC_SQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TR_FC
BEFORE INSERT ON FOODCOMMENTS
FOR EACH ROW
BEGIN
	SELECT FC_SQ.NEXTVAL INTO :NEW.FCID FROM DUAL;
END;
/